[versions]
# libraries
coroutines = "1.10.2"
material3 = "1.4.0"
materialIconsExtended = "1.7.8"
uiTooling = "1.10.0"
navigationCompose = "2.9.6"
kotlinxSerialization = "1.9.0"
lifecycle = "2.10.0"
javaxInject = "1"
kotlinxCollectionsImmutable = "0.4.0"

hiltNavigationCompose = "1.3.0"

retrofit = "3.0.0"
okhttp = "5.3.2"

room = "2.8.4"

coil = "2.7.0"
timber = "5.0.1"

mapsCompose = "7.0.0"
playServicesMaps = "19.2.0"
playServicesLocation = "21.3.0"

# testing
junit4 = "4.13.2"
junitExt = "1.3.0"
runner = "1.7.0"
truth = "1.4.5"
mockk = "1.14.7"
kotlinTest = "2.3.0"


# plugins
agp = "8.13.2"
kotlin = "2.3.0"
versionsCheck = "0.53.0"
hilt = "2.57.2"
ksp = "2.3.4"
detekt = "1.23.8"
ktlint = "14.0.1"
material = "1.13.0"

[libraries]

# Coroutines
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

# UI
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }

androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }

# Lifecycle
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }

# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }

# Javax
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javaxInject" }


# Retrofit & OkHttp
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

# Room
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }


# Tools
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

maps-compose = { module = "com.google.maps.android:maps-compose", version.ref = "mapsCompose" }
maps-compose-utils = { module = "com.google.maps.android:maps-compose-utils", version.ref = "mapsCompose" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }

# Testing
junit4 = { module = "junit:junit", version.ref = "junit4" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitExt" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlinTest" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
versionsCheck = { id = "com.github.ben-manes.versions", version.ref = "versionsCheck" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
